name: Django CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    services:
      db:
        image: nouchka/sqlite3
        volumes:
          - sqlite_data:/var/lib/sqlite3

    env:
      DATABASE_NAME: db.sqlite3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install

    - name: Linting
      run: ruff check

    - name: Code Formatting
      run: ruff format --check

    - name: Run Migrations
      run: poetry run python manage.py migrate

    - name: Run tests
      run: poetry run pytest
